-- Script generated by ChatGPT to drop all constraints and tables in the database.
-- This script is used to reset the Azure SQL database without dropping the database itself.
DECLARE @TableName NVARCHAR(128)
DECLARE TableCursor CURSOR FOR
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'

OPEN TableCursor
FETCH NEXT FROM TableCursor INTO @TableName

WHILE @@FETCH_STATUS = 0
BEGIN
    DECLARE @Sql NVARCHAR(MAX)

    -- Generate SQL to drop foreign key constraints
    SET @Sql = ''
    SELECT @Sql = @Sql + 'ALTER TABLE ' + OBJECT_NAME(f.parent_object_id) + ' DROP CONSTRAINT ' + f.name + CHAR(13)
    FROM sys.foreign_keys AS f
    WHERE OBJECT_NAME(f.referenced_object_id) = @TableName

    -- Generate SQL to drop the table
    SET @Sql = @Sql + 'DROP TABLE ' + @TableName + CHAR(13)

    -- Execute the generated SQL
    EXEC(@Sql)

    FETCH NEXT FROM TableCursor INTO @TableName
END

CLOSE TableCursor
DEALLOCATE TableCursor
